name: Build docker image

on:
  workflow_call:
    inputs:
      push_to_ghcr:
        description: 'Push to ghcr'
        default: false
        required: false
        type: boolean
    secrets:
      PAT:
        description: 'A token passed from the caller workflow'
        required: false
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/andy-grigg/meal-planner-bot
          tags: |
            type=pep440,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Docker Hub
        if: ${{ inputs.push_to_ghcr }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build (and push)
        uses: docker/build-push-action@v3
        with:
          push: ${{ inputs.push_to_ghcr }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  